version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always

  web:
    build: ./backend
    container_name: django-app
    command: /app/init_setup.sh python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
